# Generated by Django 5.1.5 on 2025-01-14 19:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit_measure', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='prixdeproduit',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='type_de_produit',
        ),
        migrations.AlterField(
            model_name='cart',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_products', to='incp.cart'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='weighting',
            field=models.DecimalField(decimal_places=2, help_text='Pondération du produit dans le panier (en %)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='commune',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='commune',
            name='moughataa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commune_set', to='incp.moughataa'),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='label',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='moughataa',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moughataa_set', to='incp.wilaya'),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('type', models.CharField(choices=[('supermarket', 'Supermarché'), ('market', 'Marché'), ('shop', 'Boutique'), ('other', 'Autre')], max_length=20)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points_of_sale', to='incp.commune')),
            ],
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_products', to='incp.product'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField(blank=True, null=True)),
                ('point_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_prices', to='incp.pointofsale')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='incp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='incp.producttype'),
        ),
        migrations.DeleteModel(
            name='PointDeVente',
        ),
        migrations.DeleteModel(
            name='PrixDeProduit',
        ),
        migrations.DeleteModel(
            name='TypeDeProduit',
        ),
        migrations.DeleteModel(
            name='Produit',
        ),
    ]
