# Generated by Django 4.2.18 on 2025-01-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incp', '0002_convert_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='date_from',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='date_to',
            field=models.DateField(default='2099-12-31'),
        ),
    ]
