# Generated by Django 5.1.5 on 2025-01-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incp', '0002_product_producttype_remove_prixdeproduit_produit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofsale',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
