# Generated by Django 4.2.18 on 2025-01-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incp', '0003_alter_productprice_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='date_to',
            field=models.DateField(default='2099-01-31'),
        ),
    ]
