version: '3.8'

services:
  web:
    build:
      context: .
    container_name: django_app
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:23021"
    volumes:
      - .:/app
    ports:
      - "23021:23021"
    depends_on:
      - mysql_db_23021
    environment:
      - DEBUG=1
      - DB_NAME=inpc
      - DB_USER=root
      - DB_PASSWORD=23021
      - DB_HOST=mysql_db_23021
      - DB_PORT=3306

  mysql_db_23021:
    image: mysql:8.0
    ports:
      - "24021:3306"
    container_name: mysql_db_23021
    environment:
      MYSQL_ROOT_PASSWORD: 23021
      MYSQL_DATABASE: inpc
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
